name: Build and Push Docker Image for MASTER branch

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/kino-cat-torrent-go:beta-latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/kino-cat-torrent-go:alpha
            ${{ secrets.DOCKER_HUB_USERNAME }}/kino-cat-torrent-go:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/kino-cat-torrent-go:latest

      - name: Complete
        run: |
          echo "Docker image published with tags: latest and ${{ github.ref_name }}"
